<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\File;

/**
 * RepositoryServiceProvider
 *
 * Auto-binds Service and Repository interfaces to their implementations.
 * Updated automatically by smart:crud when new features are generated.
 *
 * Pattern: {Model}ServiceInterface::class => {Model}Service::class
 *          {Model}RepositoryInterface::class => {Model}Repository::class
 */
class RepositoryServiceProvider extends ServiceProvider
{
    /**
     * Manual bindings — populated automatically by smart:crud.
     *
     * @var array<string, string>
     */
    public array $bindings = [
        // Example (auto-generated by smart:crud):
        // \App\Services\Contracts\ProductServiceInterface::class    => \App\Services\ProductService::class,
        // \App\Repositories\Contracts\ProductRepositoryInterface::class => \App\Repositories\ProductRepository::class,
    ];

    /**
     * Register services.
     */
    public function register(): void
    {
        // Bind manual entries
        foreach ($this->bindings as $interface => $implementation) {
            $this->app->bind($interface, $implementation);
        }

        // Auto-discover app-level services
        $this->autoDiscoverBindings(
            app_path('Services'),
            'App\\Services',
            app_path('Services/Contracts'),
            'App\\Services\\Contracts'
        );

        // Auto-discover app-level repositories
        $this->autoDiscoverBindings(
            app_path('Repositories'),
            'App\\Repositories',
            app_path('Repositories/Contracts'),
            'App\\Repositories\\Contracts'
        );

        // Auto-discover module-level bindings
        $this->discoverModuleBindings();
    }

    /**
     * Scan implementation files and bind to their matching interface.
     */
    protected function autoDiscoverBindings(
        string $implementationPath,
        string $implementationNs,
        string $contractPath,
        string $contractNs
    ): void {
        if (! File::exists($implementationPath)) {
            return;
        }

        foreach (File::files($implementationPath) as $file) {
            $class     = $implementationNs . '\\' . $file->getBasename('.php');
            $interface = $contractNs . '\\' . $file->getBasename('.php') . 'Interface';

            if (interface_exists($interface) && class_exists($class)) {
                $this->app->bind($interface, $class);
            }
        }
    }

    /**
     * Auto-discover bindings inside all Modules.
     */
    protected function discoverModuleBindings(): void
    {
        $modulesPath = base_path('Modules');

        if (! File::exists($modulesPath)) {
            return;
        }

        foreach (File::directories($modulesPath) as $modulePath) {
            $moduleName = basename($modulePath);

            $this->autoDiscoverBindings(
                "{$modulePath}/Services",
                "Modules\\{$moduleName}\\Services",
                "{$modulePath}/Services/Contracts",
                "Modules\\{$moduleName}\\Services\\Contracts"
            );

            $this->autoDiscoverBindings(
                "{$modulePath}/Repositories",
                "Modules\\{$moduleName}\\Repositories",
                "{$modulePath}/Repositories/Contracts",
                "Modules\\{$moduleName}\\Repositories\\Contracts"
            );
        }
    }
}
